### ISSUE TITLE
getBreslowJumps = TRUE triggers a crash

### ISSUE THREAD

**Issue by carbocation** [erickawaguchi/fastcmprsk#10]
Version: ‘fastcmprsk_1.1.2.tar.gz’

I have a ~50,000 row chunk of data. I get the following error until I turn off getBreslowJumps, or until I cut down to 5665 entries. I've manually inspected the 5666th entry and there is nothing unusual about it (no missingness, new values, etc). Unfortunately I can't share the data to help reproduce. However, I'm showing the error message in case this is at all helpful.

```
Warning message in rev(unique(bjump[[8]])) * table(dat$ftime[dat$fstatus == 1], :
“longer object length is not a multiple of shorter object length”
Error in as.vector(rev(unique(bjump[[8]])) * table(dat$ftime[dat$fstatus == : dims [product 206] do not match the length of object [207]
```

Traceback:
```R
1. summary(fast.fine.and.gray(at.risk))
2. fast.fine.and.gray(at.risk)
3. fastCrr(Crisk(at.risk$disease_free_survival, at.risk$competing_risks, 
 .     silent = FALSE) ~ as.matrix(at.risk[, c("enroll_age", "is_female", 
 .     "PC1")], nrow = nrow(at.risk)), variance = TRUE, returnDataFrame = TRUE)   # at line 44-47 of file <text>
4. data.frame(time = unique(rev(dat$ftime[dat$fstatus == 1])), jump = as.vector(rev(unique(bjump[[8]])) * 
 .     table(dat$ftime[dat$fstatus == 1], dat$fstatus[dat$fstatus == 
 .         1])))
5. as.vector(rev(unique(bjump[[8]])) * table(dat$ftime[dat$fstatus == 
 .     1], dat$fstatus[dat$fstatus == 1]))
```

**Comment by erickawaguchi** [comment]
@carbocation Thanks for bringing this to my attention! It'll be hard to diagnose without seeing the actual data. I haven't had any issues with this _yet_ but there may always be some tricky situations that I did not account for.  I believe the issue occurs after parameter estimation. I then use R to calculate the Breslow jumps based on observed the failure times (I believe there's an issue with the ordering here). 

Since I don't have access to your data, it's hard for me to identify the issue. I would encourage you to go directly into the source code. There is a mismatch in the length between the observed event times and the number of jumps calculated. Let me know if there is anything else I can do.

**Comment by carbocation** [comment]
Thanks for your kind reply. The dimensionality of the data is about 50k rows and 15 columns. However, I could reproduce this even after limiting the covariate matrix to just 1 column. I simulated some data so that I could share it, but so far I have only encountered the bug when I use my real data.

One question, looking at the breslow jumps - that code appears to force them to be unique. I don’t fully understand that aspect of the code, but I wonder if there is something about my data that permits them to be duplicated (so that making them unique causes a mismatch in length).

Will keep trying to find a simulated set that repros this issue so that I can share it.

**Comment by carbocation** [comment]
So, I thought I had generated a nice reproducible example for you and wrote it out to a csv. However, when I load the csv to reproduce the issue, the version loaded from csv works fine...

At first, I thought that perhaps there was some trivial numerical difference that occurred due to storing/loading, so I wrote out the objects using `dput` (both the original that I'm dumping to csv, and the new object loaded from csv). But there is no difference between them when I `diff`, aside from where their pointers are stored. 

I don't run into anything like this when I use any of the usual R regression tools, so I can't help but think that this might still somehow be an issue with the breslow jump code, but I don't think I'm closer to understanding what exactly is the trigger. While dumping to csv and reloading that is a workaround, of sorts, it feels wrong.

**Comment by carbocation** [comment]
Ways that I can get this to run:
1. Save to disk then reload
1. Round my time value. If I round it to 6 decimal places, I am perturbing the overall sum by 1 part in 10<sup>10</sup>, but this also gets the method to run without crashing. For now, I'll go with this solution. I still don't understand why this is triggering the problem, or whether this is working for me due to some side effect that I'm not correctly understanding.

**Comment by erickawaguchi** [comment]
That's very interesting. For now, I will close thread but will continue to see if something is wrong. It might be possible that in very tail cases where you don't round, R is confusing the time values that are not rounded (but close) to being the same value? Is it possible for you to only share the time vector with me? I gave my email in the other thread you opened. PS: Are the coefficient estimates the same with both ```fastCrr``` and ```crr```?
